### ISSUE TITLE
Products.PloneHotfix20171128

### ISSUE THREAD

**Issue by ale-rt** [jone/plone-hotfixes#11]
Looking at https://plone.org/security/hotfix/20171128 it seems the last affected version of Plone is 5.1rc1.
I am not really sure about this, anyway if this is the case I would just make a change to this line:
https://github.com/jone/plone-hotfixes/blob/2d4ce9ffe2007375118515848e286df3edc1ae24/hotfixes.js#L8

**Comment by jone** [comment]
@ale-rt thanks for reporting; I've prepared an update in #12 .

**Comment by ale-rt** [comment]
Thank you for this amazing tool :)

**Comment by jone** [comment]
> Thank you for this amazing tool :)

Thank you!

The change is now deployed.

Cheers
