### ISSUE TITLE
add "Plone Hotfix 20150910 (Sep 10, 2015)"

### ISSUE THREAD

**Issue by thet** [jone/plone-hotfixes#2]
https://plone.org/products/plone-hotfix/releases/20150910

**Comment by jone** [comment]
@thet thanks for reporting, I've added the newest hotfix.

**Comment by thet** [comment]
welcome and tnx!
the release 4.3.7 doesn't need the hotfix anymore.

**Comment by jone** [comment]
Thanks for reporting, I've added the Plone 4.3.7 version test and marked the hotfix as fixed there (6a32e51537fc340241f8cc0c3093159944324ae1 and e7f6049a2fe80455416b4ba4159d4cbb6d29d17c)
