### ISSUE TITLE
Add PloneHotfix20151208

### ISSUE THREAD

**Issue by mauritsvanrees** [jone/plone-hotfixes#4]
Can you add today's hotfix?
https://plone.org/products/plone-hotfix/releases/20151208
It is for every current Plone site, so until and including 4.3.7 and 5.0.
The relevant fix has already been added in PlonePAS, and will be included in 4.3.8 and 5.0.1.
Thanks.

**Comment by maethu** [comment]
I'll try :smile:

**Comment by maethu** [comment]
Thanks @mauritsvanrees I've added PloneHotfix20151208!

**Comment by mauritsvanrees** [comment]
Thanks! I see it is working.

Oh, I would show this one for _all_ versions. Officially it is only supported on Plone 4 and 5, but that is simply our version policy. There are no technical reasons that this would not work on earlier versions.
Plone 2.0 is not affected. Plone 2.1 to 3.3 are affected.
Note that I am on the Plone Security Team, so you have my blessing to add 2.1-3.3 here. :-)

**Comment by maethu** [comment]
> Note that I am on the Plone Security Team, so you have my blessing to add 2.1-3.3 here. :-)

hehe I'm aware of that :smiley: 

I did the update, hope it's fine now.

**Comment by mauritsvanrees** [comment]
Perfect, thanks!
